version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/sveltekit"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/hono"
    schedule:
      interval: "weekly"
